image: ubuntu:xenial

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y libreadline6-dev libncurses5-dev perl clang g++ g++-mingw-w64-i686 g++-mingw-w64-x86-64 qemu-system-x86
    - ./.ci/travis/prepare.sh
    - ./.ci/travis/build.sh

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  SETUP_PATH: ".ci-local:.ci"
  BASE: "7.0"
  SET: "latest"
