image: ubuntu:bionic

cache:
  paths:
    - /root/.cache

build:
  stage: build
  script:
    - mkdir -p /root/.cache
    - apt-get update
    - apt-get install -y libreadline6-dev libncurses5-dev perl clang g++ make git
    - apt-get install -y sudo python-pip python3-pip netcat
    - ./.compile-epics.sh
    - test/install-pytest-pyepics-p4p.sh
    - test/test-pytest-pyepics-p4p.sh
    - make -C test test-ioc-with-sim
    - make -C test test-ioc-with-sim-indexer

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  SETUP_PATH: ".ci-local:.ci"
  BASE: "3.15"
  SET: latest
