image: ubuntu:xenial

build:
  stage: build
  script:
    - apt install -y libreadline6-dev libncurses5-dev perl clang g++-mingw-w64-i686 g++-mingw-w64-x86-64 qemu-system-x86
    - ./.ci/travis/prepare.sh
    - ./.ci/travis/build.sh
