#https://confluence.esss.lu.se/display/CSI/Software+Quality
#
# What is needed as well:
# https://pre-commit.com/
# pip install pre-commit

repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
#  - repo: https://gitlab.com/pycqa/flake8
#    rev: 3.8.3
#    hooks:
#      - id: flake8
