sudo: false
dist: trusty
language: c
compiler:
  - gcc
cache:
  directories:
    - $HOME/.cache
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
    - re2c
env:
 - BASE=3.14 STATIC=shared SEQ=2.2.6 ASYN=R4-35 IPAC=2.15 MODBUS=R2-11 MOTOR=v7.0.1-ESS
 - BASE=3.14 STATIC=static SEQ=2.2.6 ASYN=R4-35 IPAC=2.15 MODBUS=R2-11 MOTOR=v7.0.1-ESS
 - BASE=R3.15.6 STATIC=shared SEQ=2.2.6 ASYN=R4-35 IPAC=2.15 MODBUS=R2-11 MOTOR=v7.0.1-ESS
 - BASE=R3.15.6 STATIC=static SEQ=2.2.6 ASYN=R4-35 IPAC=2.15 MODBUS=R2-11 MOTOR=v7.0.1-ESS
 - BASE=7.0 STATIC=shared RTEMS=4.10 SEQ=2.2.6 ASYN=R4-35 IPAC=2.15 MODBUS=R2-11 MOTOR=v7.0.1-ESS
 - BASE=7.0 STATIC=shared CMPLR=clang WINE=32 SEQ=2.2.4 ASYN=R4-35 IPAC=  MODBUS=R2-11 MOTOR=v7.0.1-ESS
 - BASE=7.0 STATIC=static WINE=32 SEQ=2.2.6 ASYN=R4-35 IPAC=  MODBUS=R2-11 MOTOR=v7.0.1-ESS
install: ./.ci/travis-prepare.sh
before_script:
  - cp ./configure/EXAMPLE_CONFIG_SITE.local ./configure/CONFIG_SITE.local
script: make
