sudo: false
dist: bionic
language: c
compiler:
  - gcc
cache:
  directories:
    - $HOME/.cache
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
    - re2c
env:
# - BASE=3.14    STATIC=shared                     ASYN=R4-35 MOTOR=v7.0.1-ESS
# - BASE=R3.15.6 STATIC=shared                     ASYN=R4-35 MOTOR=v7.0.1-ESS
 - BASE=7.0     STATIC=shared                     ASYN=R4-35 MOTOR=v7.0.1-ESS
# - BASE=3.14    STATIC=static                     ASYN=R4-35 MOTOR=v7.0.1-ESS
# - BASE=R3.15.6 STATIC=static                     ASYN=R4-35 MOTOR=v7.0.1-ESS
# - BASE=7.0     STATIC=static                     ASYN=R4-35 MOTOR=v7.0.1-ESS
install: ./.ci-ethercatmc/travis-prepare.sh
script: make
