name: shellcheck
on:
  push:
jobs:
    shellcheck:
      runs-on: ubuntu-latest
      steps:
        - name: Run shellcheck
        - uses: actions/checkout@v4
        - uses: ludeeus/action-shellcheck@master
          with:
            version: v0.9.0
        run: |
            ./checkshellcheck.sh
